### PR TITLE
Adding functions and tests for extremes

### LINKED ISSUE #52: Create functions for Extreme events
Create functions for extreme events as discussed in 2023.12.14 meeting

### PR DESCRIPTION
**Pull request by lilyclements**
fixes #52

### CODE REVIEW

**Comment by lilyclements** [comment]
@ChrisMarsh82 which function are you referring to? There are three functions - 

`extremes_rain`, `extremes_tmin`, `extremes_tmax`

So to do minimum temperature extremes then you use the `extremes_tmin` function.

There is a test on this under the testthat files which runs through using these functions

**Comment by ChrisMarsh82** [comment]
I call overall_extremes_summaries and pass in the country and station. I also pass in the summary needed. If I pass in extremes_rain it works fine. If I pass in extremes_rain and extremese_tmin it works if I just pass in extremes_tmin it returns as error.

**Comment by lilyclements** [comment]
The other functions are wrappers to `overall_extremes_summaries`, so we wouldn't be calling `overall_extremes_summaries` directly in the API. As a result, this function works internally in the `epicsawrap` package. I'm not sure if you're testing in R or elsewhere, but just as an FYI. This is to work consistently with `total_temperature_summaries` as discussed in issue #1.

But that's odd you're getting an issue. What data are you testing that on? It works for me on `test_1` because it's all defined in the definitions there. Check the definitions of the data you're testing it on to see if it's defined in there. 

image

**Comment by ChrisMarsh82** [comment]
I call epicsawrap.overall_extremes_summaries with these variables
```
        "country": "zm",
        "station_id": "test_1",
        "summaries": [
            "extremes_tmin"
        ],
```

**Comment by lilyclements** [comment]
Can you try with `extremes_tmin` out of interest? Presumably that won't work if this overall isn't working.

Does `extremes_tmax` work?

And is everything updated in `rpicsa`, and `epicsawrap` (and `epicsadata`, although that one shouldn't be a problem.)

**Pull request merged**
